---
production:
  fb_app_id: WEdyMXp0c2VTVmh6emJFUFgyMlRxaFA2RUUzWEpnUjdoTHZPNzFBR1Q3Zz0tLUVESmwrMmZ5enpNQThBejRGNG1TWUE9PQ==--ae833feac92322f9b92a0990e20aba199f26a5ed
  fb_secret_id: Z0QzNlh4bU02NUpBQzgrbkxTSUU0OUhVNlNyOGtZTzZ0dGFBd1lMajVCWT0tLXdBcWFpNEJndkFqUW5ZbTk5NU1ibUE9PQ==--55da3d3278eecc28e73931358de322b89d01ab13
development:
  fb_app_id: bkpuUlhCNnNTdERxS0V0R1Z6bExBRHdrdmJWV2VSeEIxcGc0aVVZdVVwUT0tLWwvdE1WVzdzRlYvOU5FMDRQNXlXZmc9PQ==--bd25d0370c89ebed7476fb7a18f3b061d6b8af22
  fb_secret_id: ZDQxWHRFR0RXOUx4UExGbE5ZQXFkMm1DMEtVRVV5RnRIN1pGM0hBc3RhVT0tLWhHd3VRcHptYVNjdWZUNjl5c1pnWWc9PQ==--1f7125b66401150f05eace508ec00b164f5834f1
