---
production:
  fb_app_id: amx3bjl1ZjE2d1VKMm81WFkyZDJyUT09LS1WM0tUY2FoczMzSUFjbXNHMGZGSWZ3PT0=--30e82d10982a6524044e56e1aae9bba30e9af976
  fb_secret_id: UU5JblhaUnl4UmlKVkNSaTJjQkFDRHQ1aDVYVy9NVG12WXkxeDZUVGlQVnV5TUtxRk84TEtReWRvWit4UFhmZC0tVFZhNGhYTnlUbEdKRmxTdzZmbzN4Zz09--159f30fde757318c5146e0e99e24fba0638f1b84
development:
  fb_app_id: ejZzRlV0aG9LYjV0cGtDVnRnOVI2Zz09LS14UWFrRThiWjYrT2NoeEc3OFVxYnBBPT0=--bb5ad5d8b6cd17811406b9d592441fd179f2f9ca
  fb_secret_id: dlRKaU9yQmd0V1VMR0xwZjR3UFFoRkdSZDNMUHFqMjUyOWNBM05abjNmcTE3a1FNSU0wQWlncDVzZWJjZXJicy0tbk94bUhrNDRORWtDMXNPZExSZjdpdz09--04cfa7d1bceb581a41f960c18c4a23d59541f9b0
